defmodule TennisTracker.Repo.Migrations.NullableSeasonRulesFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:season_rules) do
      modify :on_level_min_pct, :decimal, null: true
      modify :max_roster, :bigint, null: true
      modify :min_roster, :bigint, null: true
    end
  end

  def down do
    alter table(:season_rules) do
      modify :min_roster, :bigint, null: false
      modify :max_roster, :bigint, null: false
      modify :on_level_min_pct, :decimal, null: false
    end
  end
end
