defmodule TennisTracker.Repo.Migrations.UpdateMatchIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:matches, [:team_id, :match_date])

    create index(:matches, [:team_id, :match_start_datetime])
  end

  def down do
    drop_if_exists index(:matches, [:team_id, :match_start_datetime])

    create index(:matches, [:team_id, :match_date])
  end
end
