defmodule TennisTracker.Repo.Migrations.AddLocationsAndMatches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:matches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :match_date, :date, null: false
      add :match_time, :time, null: false
      add :timezone, :text, null: false, default: "America/Chicago"
      add :duration_minutes, :bigint, null: false, default: 90
      add :opponent, :text, null: false
      add :home_or_away, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :team_id,
          references(:teams,
            column: :id,
            name: "matches_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :location_id, :uuid
    end

    create index(:matches, [:team_id, :match_date])

    create table(:locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:matches) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "matches_location_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:locations) do
      add :name, :text, null: false
      add :address, :text, null: false
      add :google_maps_url, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:locations, [:name], name: "locations_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:locations, [:name], name: "locations_unique_name_index")

    alter table(:locations) do
      remove :updated_at
      remove :inserted_at
      remove :google_maps_url
      remove :address
      remove :name
    end

    drop constraint(:matches, "matches_location_id_fkey")

    alter table(:matches) do
      modify :location_id, :uuid
    end

    drop table(:locations)

    drop constraint(:matches, "matches_team_id_fkey")

    drop_if_exists index(:matches, [:team_id, :match_date])

    drop table(:matches)
  end
end
