defmodule TennisTracker.Repo.Migrations.AddTeamDefaultTimezone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      add :default_timezone, :text, default: "America/Chicago"
    end
  end

  def down do
    alter table(:teams) do
      remove :default_timezone
    end
  end
end
