defmodule TennisTracker.Repo.Migrations.NullableTeamTypeFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:team_types) do
      modify :ntrp_level, :decimal, null: true
      modify :age_group, :text, null: true
    end
  end

  def down do
    alter table(:team_types) do
      modify :age_group, :text, null: false
      modify :ntrp_level, :decimal, null: false
    end
  end
end
