defmodule TennisTracker.Repo.Migrations.AddTeamMembershipsContextIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:team_memberships, [:team_type_id, :season_year])
  end

  def down do
    drop_if_exists index(:team_memberships, [:team_type_id, :season_year])
  end
end
