defmodule TennisTracker.Repo.Migrations.DropPlayerPerMatchAddPlayerPerSlotPerMatch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:match_lineup_assignments, [:group_id, :match_id, :player_id],
                     name: "match_lineup_assignments_player_per_match_index"
                   )

    create unique_index(
             :match_lineup_assignments,
             [:group_id, :match_id, :player_id, :team_lineup_slot_id],
             name: "match_lineup_assignments_player_per_slot_per_match_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :match_lineup_assignments,
                     [:group_id, :match_id, :player_id, :team_lineup_slot_id],
                     name: "match_lineup_assignments_player_per_slot_per_match_index"
                   )

    create unique_index(:match_lineup_assignments, [:group_id, :match_id, :player_id],
             name: "match_lineup_assignments_player_per_match_index"
           )
  end
end
