defmodule TennisTracker.Repo.Migrations.AddCascadeDeleteToTeamLineupFks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:team_lineup_slots, "team_lineup_slots_team_id_fkey")

    alter table(:team_lineup_slots) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_lineup_slots_team_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:team_lineup_columns, "team_lineup_columns_team_id_fkey")

    alter table(:team_lineup_columns) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_lineup_columns_team_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:team_lineup_columns, "team_lineup_columns_team_id_fkey")

    alter table(:team_lineup_columns) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_lineup_columns_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:team_lineup_slots, "team_lineup_slots_team_id_fkey")

    alter table(:team_lineup_slots) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_lineup_slots_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
