defmodule TennisTracker.Repo.Migrations.RemoveTeamCaptain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      remove :captain
    end
  end

  def down do
    alter table(:teams) do
      add :captain, :text
    end
  end
end
