defmodule TennisTracker.Repo.Migrations.StructuredLocationAddress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:locations) do
      remove :address
      add :street_address, :text
      add :city, :text
      add :state, :text
      add :postal_code, :text
    end
  end

  def down do
    alter table(:locations) do
      remove :postal_code
      remove :state
      remove :city
      remove :street_address
      add :address, :text, null: false
    end
  end
end
