defmodule TennisTracker.Repo.Migrations.AddTeamRole do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:team_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :group_id, :uuid, null: false
      add :role, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "team_roles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :team_id,
          references(:teams,
            column: :id,
            name: "team_roles_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:team_roles, [:group_id, :user_id, :team_id],
             name: "team_roles_unique_user_team_index"
           )
  end

  def down do
    drop_if_exists unique_index(:team_roles, [:group_id, :user_id, :team_id],
                     name: "team_roles_unique_user_team_index"
                   )

    drop constraint(:team_roles, "team_roles_user_id_fkey")

    drop constraint(:team_roles, "team_roles_team_id_fkey")

    drop table(:team_roles)
  end
end
