defmodule TennisTracker.Repo.Migrations.AddLineupColumnsAndAssignmentMode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      add :lineup_assignment_mode, :text, null: false, default: "one_per_match"
    end

    alter table(:team_lineup_slots) do
      add :is_exclusion_slot, :boolean, null: false, default: false
      add :team_lineup_column_id, :uuid
    end

    create table(:team_lineup_columns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:team_lineup_slots) do
      modify :team_lineup_column_id,
             references(:team_lineup_columns,
               column: :id,
               name: "team_lineup_slots_team_lineup_column_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:team_lineup_columns) do
      add :name, :text, null: false
      add :sort_order, :bigint, null: false, default: 0
      add :group_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :team_id,
          references(:teams,
            column: :id,
            name: "team_lineup_columns_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:team_lineup_columns, [:group_id, :team_id, :name],
             name: "team_lineup_columns_unique_column_name_per_team_index"
           )
  end

  def down do
    drop_if_exists unique_index(:team_lineup_columns, [:group_id, :team_id, :name],
                     name: "team_lineup_columns_unique_column_name_per_team_index"
                   )

    drop constraint(:team_lineup_columns, "team_lineup_columns_team_id_fkey")

    alter table(:team_lineup_columns) do
      remove :team_id
      remove :updated_at
      remove :inserted_at
      remove :group_id
      remove :sort_order
      remove :name
    end

    drop constraint(:team_lineup_slots, "team_lineup_slots_team_lineup_column_id_fkey")

    alter table(:team_lineup_slots) do
      modify :team_lineup_column_id, :uuid
    end

    drop table(:team_lineup_columns)

    alter table(:team_lineup_slots) do
      remove :team_lineup_column_id
      remove :is_exclusion_slot
    end

    alter table(:teams) do
      remove :lineup_assignment_mode
    end
  end
end
