defmodule TennisTracker.Repo.Migrations.ReplaceExclusionSlotWithParticipationType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:team_lineup_slots) do
      add :participation_type, :text, null: true
    end

    execute(
      "UPDATE team_lineup_slots SET participation_type = 'out' WHERE is_exclusion_slot = true"
    )

    execute(
      "UPDATE team_lineup_slots SET participation_type = 'playing' WHERE is_exclusion_slot = false OR is_exclusion_slot IS NULL"
    )

    alter table(:team_lineup_slots) do
      modify :participation_type, :text, null: false, default: "playing"
      remove :is_exclusion_slot
    end
  end

  def down do
    alter table(:team_lineup_slots) do
      add :is_exclusion_slot, :boolean, null: true
    end

    execute(
      "UPDATE team_lineup_slots SET is_exclusion_slot = true WHERE participation_type = 'out'"
    )

    execute(
      "UPDATE team_lineup_slots SET is_exclusion_slot = false WHERE participation_type != 'out'"
    )

    alter table(:team_lineup_slots) do
      modify :is_exclusion_slot, :boolean, null: false, default: false
      remove :participation_type
    end
  end
end
