defmodule TennisTracker.Repo.Migrations.TeamLineupSlots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:team_lineup_slots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :expected_count, :bigint
      add :sort_order, :bigint, null: false, default: 0
      add :include_in_clipboard, :boolean, null: false, default: true
      add :group_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :team_id,
          references(:teams,
            column: :id,
            name: "team_lineup_slots_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:team_lineup_slots, [:group_id, :team_id, :name],
             name: "team_lineup_slots_unique_slot_name_per_team_index"
           )

    create table(:match_lineup_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :group_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :match_id,
          references(:matches,
            column: :id,
            name: "match_lineup_assignments_match_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :player_id,
          references(:players,
            column: :id,
            name: "match_lineup_assignments_player_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :team_lineup_slot_id,
          references(:team_lineup_slots,
            column: :id,
            name: "match_lineup_assignments_team_lineup_slot_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:match_lineup_assignments, [:group_id, :match_id, :player_id],
             name: "match_lineup_assignments_player_per_match_index"
           )
  end

  def down do
    drop_if_exists unique_index(:match_lineup_assignments, [:group_id, :match_id, :player_id],
                     name: "match_lineup_assignments_player_per_match_index"
                   )

    drop constraint(:match_lineup_assignments, "match_lineup_assignments_match_id_fkey")

    drop constraint(:match_lineup_assignments, "match_lineup_assignments_player_id_fkey")

    drop constraint(
           :match_lineup_assignments,
           "match_lineup_assignments_team_lineup_slot_id_fkey"
         )

    drop table(:match_lineup_assignments)

    drop_if_exists unique_index(:team_lineup_slots, [:group_id, :team_id, :name],
                     name: "team_lineup_slots_unique_slot_name_per_team_index"
                   )

    drop constraint(:team_lineup_slots, "team_lineup_slots_team_id_fkey")

    drop table(:team_lineup_slots)
  end
end
