defmodule TennisTracker.Repo.Migrations.AddTeamRosterTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:teams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :captain, :text
      add :season_year, :bigint, null: false
      add :is_pseudo, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :team_type_id, :uuid, null: false
    end

    create index(:teams, [:team_type_id, :season_year])

    create index(:teams, [:season_year])

    create table(:team_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:teams) do
      modify :team_type_id,
             references(:team_types,
               column: :id,
               name: "teams_team_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:team_types) do
      add :name, :text, null: false
      add :age_group, :text, null: false
      add :ntrp_level, :decimal, null: false
      add :allowed_ntrp_levels, {:array, :decimal}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:team_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :team_type_id, :uuid, null: false
      add :season_year, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :player_id,
          references(:players,
            column: :id,
            name: "team_memberships_player_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :team_id,
          references(:teams,
            column: :id,
            name: "team_memberships_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:team_memberships, [:player_id, :team_type_id, :season_year],
             name: "team_memberships_unique_player_context_index"
           )

    create table(:season_rules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :season_year, :bigint, null: false
      add :min_roster, :bigint, null: false
      add :max_roster, :bigint, null: false
      add :on_level_min_pct, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :team_type_id,
          references(:team_types,
            column: :id,
            name: "season_rules_team_type_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:season_rules, [:team_type_id, :season_year],
             name: "season_rules_unique_team_type_season_index"
           )
  end

  def down do
    drop_if_exists unique_index(:season_rules, [:team_type_id, :season_year],
                     name: "season_rules_unique_team_type_season_index"
                   )

    drop constraint(:season_rules, "season_rules_team_type_id_fkey")

    drop table(:season_rules)

    drop_if_exists unique_index(:team_memberships, [:player_id, :team_type_id, :season_year],
                     name: "team_memberships_unique_player_context_index"
                   )

    drop constraint(:team_memberships, "team_memberships_player_id_fkey")

    drop constraint(:team_memberships, "team_memberships_team_id_fkey")

    drop table(:team_memberships)

    alter table(:team_types) do
      remove :updated_at
      remove :inserted_at
      remove :allowed_ntrp_levels
      remove :ntrp_level
      remove :age_group
      remove :name
    end

    drop constraint(:teams, "teams_team_type_id_fkey")

    alter table(:teams) do
      modify :team_type_id, :uuid
    end

    drop table(:team_types)

    drop_if_exists index(:teams, [:season_year])

    drop_if_exists index(:teams, [:team_type_id, :season_year])

    drop table(:teams)
  end
end
