defmodule TennisTracker.Repo.Migrations.AddPlayerTaggingSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :group_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tag_category_id, :uuid, null: false
    end

    create index(:tags, [:group_id, :tag_category_id, "lower(name)"],
             name: "tags_unique_name_per_category_group",
             unique: true
           )

    create table(:tag_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:tags) do
      modify :tag_category_id,
             references(:tag_categories,
               column: :id,
               name: "tags_tag_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:tag_categories) do
      add :name, :text, null: false
      add :group_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tag_categories, [:group_id, :name],
             name: "tag_categories_unique_name_per_group_index"
           )

    create table(:season_rules_default_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :season_rules_id,
          references(:season_rules,
            column: :id,
            name: "season_rules_default_tags_season_rules_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "season_rules_default_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :group_id, :uuid, null: false
    end

    create unique_index(:season_rules_default_tags, [:group_id, :season_rules_id, :tag_id],
             name: "season_rules_default_tags_unique_season_rules_tag_index"
           )

    alter table(:players) do
      remove :eligible_55_plus
      remove :eligible_40_plus
      remove :eligible_18_plus
    end

    create table(:player_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :player_id,
          references(:players,
            column: :id,
            name: "player_tags_player_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "player_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :group_id, :uuid, null: false
    end

    create unique_index(:player_tags, [:group_id, :player_id, :tag_id],
             name: "player_tags_unique_player_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:player_tags, [:group_id, :player_id, :tag_id],
                     name: "player_tags_unique_player_tag_index"
                   )

    drop constraint(:player_tags, "player_tags_player_id_fkey")

    drop constraint(:player_tags, "player_tags_tag_id_fkey")

    drop table(:player_tags)

    alter table(:players) do
      add :eligible_18_plus, :boolean, null: false, default: true
      add :eligible_40_plus, :boolean, null: false, default: false
      add :eligible_55_plus, :boolean, null: false, default: false
    end

    drop_if_exists unique_index(
                     :season_rules_default_tags,
                     [:group_id, :season_rules_id, :tag_id],
                     name: "season_rules_default_tags_unique_season_rules_tag_index"
                   )

    drop constraint(:season_rules_default_tags, "season_rules_default_tags_season_rules_id_fkey")

    drop constraint(:season_rules_default_tags, "season_rules_default_tags_tag_id_fkey")

    drop table(:season_rules_default_tags)

    drop_if_exists unique_index(:tag_categories, [:group_id, :name],
                     name: "tag_categories_unique_name_per_group_index"
                   )

    alter table(:tag_categories) do
      remove :updated_at
      remove :inserted_at
      remove :group_id
      remove :name
    end

    drop constraint(:tags, "tags_tag_category_id_fkey")

    alter table(:tags) do
      modify :tag_category_id, :uuid
    end

    drop table(:tag_categories)

    drop_if_exists index(:tags, [:group_id, :tag_category_id, "lower(name)"],
                     name: "tags_unique_name_per_category_group"
                   )

    drop table(:tags)
  end
end
