defmodule TennisTracker.Repo.Migrations.FinalizeMatchStartDatetime do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:matches) do
      remove :match_time
      remove :match_date
      modify :match_start_datetime, :utc_datetime, null: false
    end
  end

  def down do
    alter table(:matches) do
      modify :match_start_datetime, :utc_datetime, null: true
      add :match_date, :date, null: false
      add :match_time, :time, null: false
    end
  end
end
