defmodule TennisTracker.Repo.Migrations.AddMatchStartDatetime do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:matches) do
      add :match_start_datetime, :utc_datetime
    end
  end

  def down do
    alter table(:matches) do
      remove :match_start_datetime
    end
  end
end
