defmodule TennisTracker.Repo.Migrations.AddGroupIdToTennisResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:teams, [:team_type_id, :season_year])

    drop_if_exists index(:teams, [:season_year])

    drop constraint(:teams, "teams_team_type_id_fkey")

    alter table(:teams) do
      add :group_id, :uuid, null: false
    end

    create index(:teams, [:group_id, :team_type_id, :season_year])

    create index(:teams, [:group_id, :season_year])

    alter table(:teams) do
      modify :team_type_id,
             references(:team_types,
               column: :id,
               name: "teams_team_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:team_types) do
      add :group_id, :uuid, null: false
    end

    drop constraint(:team_roles, "team_roles_team_id_fkey")

    alter table(:team_roles) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_roles_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:team_memberships, [:team_type_id, :season_year])

    drop constraint(:team_memberships, "team_memberships_team_id_fkey")

    drop constraint(:team_memberships, "team_memberships_player_id_fkey")

    alter table(:team_memberships) do
      add :group_id, :uuid, null: false
    end

    create index(:team_memberships, [:group_id, :team_type_id, :season_year])

    drop_if_exists unique_index(:team_memberships, [:player_id, :team_type_id, :season_year],
                     name: "team_memberships_unique_player_context_index"
                   )

    alter table(:team_memberships) do
      modify :player_id,
             references(:players,
               column: :id,
               name: "team_memberships_player_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_memberships_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:team_memberships, [:group_id, :player_id, :team_type_id, :season_year],
             name: "team_memberships_unique_player_context_index"
           )

    drop constraint(:season_rules, "season_rules_team_type_id_fkey")

    alter table(:season_rules) do
      add :group_id, :uuid, null: false
    end

    drop_if_exists unique_index(:season_rules, [:team_type_id, :season_year],
                     name: "season_rules_unique_team_type_season_index"
                   )

    alter table(:season_rules) do
      modify :team_type_id,
             references(:team_types,
               column: :id,
               name: "season_rules_team_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:season_rules, [:group_id, :team_type_id, :season_year],
             name: "season_rules_unique_team_type_season_index"
           )

    drop_if_exists index(:players, [:ntrp_rating, :name])

    alter table(:players) do
      add :group_id, :uuid, null: false
    end

    create index(:players, [:group_id, :ntrp_rating, :name])

    drop_if_exists index(:matches, [:team_id, :match_start_datetime])

    drop constraint(:matches, "matches_location_id_fkey")

    drop constraint(:matches, "matches_team_id_fkey")

    alter table(:matches) do
      add :group_id, :uuid, null: false
    end

    create index(:matches, [:group_id, :team_id, :match_start_datetime])

    alter table(:matches) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "matches_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :location_id,
             references(:locations,
               column: :id,
               name: "matches_location_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:locations) do
      add :group_id, :uuid, null: false
    end

    drop_if_exists unique_index(:locations, [:name], name: "locations_unique_name_index")

    create unique_index(:locations, [:group_id, :name], name: "locations_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:locations, [:group_id, :name],
                     name: "locations_unique_name_index"
                   )

    create unique_index(:locations, [:name], name: "locations_unique_name_index")

    alter table(:locations) do
      remove :group_id
    end

    drop constraint(:matches, "matches_team_id_fkey")

    drop constraint(:matches, "matches_location_id_fkey")

    alter table(:matches) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "matches_location_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :team_id,
             references(:teams,
               column: :id,
               name: "matches_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:matches, [:group_id, :team_id, :match_start_datetime])

    alter table(:matches) do
      remove :group_id
    end

    create index(:matches, [:team_id, :match_start_datetime])

    drop_if_exists index(:players, [:group_id, :ntrp_rating, :name])

    alter table(:players) do
      remove :group_id
    end

    create index(:players, [:ntrp_rating, :name])

    drop_if_exists unique_index(:season_rules, [:group_id, :team_type_id, :season_year],
                     name: "season_rules_unique_team_type_season_index"
                   )

    drop constraint(:season_rules, "season_rules_team_type_id_fkey")

    alter table(:season_rules) do
      modify :team_type_id,
             references(:team_types,
               column: :id,
               name: "season_rules_team_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:season_rules, [:team_type_id, :season_year],
             name: "season_rules_unique_team_type_season_index"
           )

    alter table(:season_rules) do
      remove :group_id
    end

    drop_if_exists unique_index(
                     :team_memberships,
                     [:group_id, :player_id, :team_type_id, :season_year],
                     name: "team_memberships_unique_player_context_index"
                   )

    drop constraint(:team_memberships, "team_memberships_player_id_fkey")

    drop constraint(:team_memberships, "team_memberships_team_id_fkey")

    alter table(:team_memberships) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_memberships_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :player_id,
             references(:players,
               column: :id,
               name: "team_memberships_player_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:team_memberships, [:player_id, :team_type_id, :season_year],
             name: "team_memberships_unique_player_context_index"
           )

    drop_if_exists index(:team_memberships, [:group_id, :team_type_id, :season_year])

    alter table(:team_memberships) do
      remove :group_id
    end

    create index(:team_memberships, [:team_type_id, :season_year])

    drop constraint(:team_roles, "team_roles_team_id_fkey")

    alter table(:team_roles) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_roles_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:team_types) do
      remove :group_id
    end

    drop constraint(:teams, "teams_team_type_id_fkey")

    alter table(:teams) do
      modify :team_type_id,
             references(:team_types,
               column: :id,
               name: "teams_team_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists index(:teams, [:group_id, :season_year])

    drop_if_exists index(:teams, [:group_id, :team_type_id, :season_year])

    alter table(:teams) do
      remove :group_id
    end

    create index(:teams, [:season_year])

    create index(:teams, [:team_type_id, :season_year])
  end
end
