defmodule TennisTracker.Repo.Migrations.AddEligibilityColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:players) do
      add :eligible_18_plus, :boolean, null: false, default: true
      add :eligible_40_plus, :boolean, null: false, default: false
      add :eligible_55_plus, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:players) do
      remove :eligible_55_plus
      remove :eligible_40_plus
      remove :eligible_18_plus
    end
  end
end
