defmodule TennisTracker.Repo.Migrations.RemoveBirthYear do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:players) do
      remove :birth_year
    end
  end

  def down do
    alter table(:players) do
      add :birth_year, :bigint
    end
  end
end
