defmodule TennisTracker.Repo.Migrations.AddLocationArchivedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:teams, "teams_team_type_id_fkey")

    alter table(:teams) do
      modify :team_type_id,
             references(:team_types,
               column: :id,
               name: "teams_team_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:team_roles, "team_roles_team_id_fkey")

    alter table(:team_roles) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_roles_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:team_memberships, "team_memberships_team_id_fkey")

    drop constraint(:team_memberships, "team_memberships_player_id_fkey")

    alter table(:team_memberships) do
      modify :player_id,
             references(:players,
               column: :id,
               name: "team_memberships_player_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_memberships_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:season_rules, "season_rules_team_type_id_fkey")

    alter table(:season_rules) do
      modify :team_type_id,
             references(:team_types,
               column: :id,
               name: "season_rules_team_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:matches, "matches_location_id_fkey")

    drop constraint(:matches, "matches_team_id_fkey")

    alter table(:matches) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "matches_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :location_id,
             references(:locations,
               column: :id,
               name: "matches_location_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:locations) do
      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:locations) do
      remove :archived_at
    end

    drop constraint(:matches, "matches_team_id_fkey")

    drop constraint(:matches, "matches_location_id_fkey")

    alter table(:matches) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "matches_location_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :team_id,
             references(:teams,
               column: :id,
               name: "matches_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:season_rules, "season_rules_team_type_id_fkey")

    alter table(:season_rules) do
      modify :team_type_id,
             references(:team_types,
               column: :id,
               name: "season_rules_team_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:team_memberships, "team_memberships_player_id_fkey")

    drop constraint(:team_memberships, "team_memberships_team_id_fkey")

    alter table(:team_memberships) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_memberships_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :player_id,
             references(:players,
               column: :id,
               name: "team_memberships_player_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:team_roles, "team_roles_team_id_fkey")

    alter table(:team_roles) do
      modify :team_id,
             references(:teams,
               column: :id,
               name: "team_roles_team_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:teams, "teams_team_type_id_fkey")

    alter table(:teams) do
      modify :team_type_id,
             references(:team_types,
               column: :id,
               name: "teams_team_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
