defmodule TennisTracker.Repo.Migrations.AddLocationUniqueNamePerGroup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:locations, [:group_id, :name],
             name: "locations_unique_name_per_group_index"
           )
  end

  def down do
    drop_if_exists unique_index(:locations, [:group_id, :name],
                     name: "locations_unique_name_per_group_index"
                   )
  end
end
