defmodule TennisTracker.Repo.Migrations.AddNtrpNameIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:players, [:ntrp_rating, :name])
  end

  def down do
    drop_if_exists index(:players, [:ntrp_rating, :name])
  end
end
